### ISSUE TITLE
Unable to load eslint in 4.13

### ISSUE THREAD

**Issue by MaxGuitet** [SublimeLinter/SublimeLinter#1663]
Since upgrading to 4.13 eslint is no longer loaded. I have a message 
```
SublimeLinter WARNING: Skipping 'eslint' for now which is listed as a devDependency in package.json but not installed.  Forgot to 'npm install'?
```
Going back to 4.12 works as expected.

Any idea ?

**Comment by kaste** [comment]
That's interesting esp. because it only logs 'package.json'. I would expect a full path to 'package.json' here. 

We need more info though. Please turn on debug mode and tell us which eslint binary it uses on 4.12.  Then switch to 4.13 and dump the log here.  Esp. working dir, top folder you have open, file_path you're linting, your OS of course.

**Comment by kaste** [comment]
In the Sublime console: What does `import os; print(os.path.expanduser('~'))` print. Or rather does this point to your actual HOME directory?

**Comment by cosmocoder** [comment]
Linting messages and color hightlights also stopped working for me after upgrading to v4.13, but I don't get the "skipping eslint" warning as mentioned by OP. How do I manually install v 4.12 and see if it fixes the linting?

**Comment by kaste** [comment]
@cosmocoder Please dump the debug output as well.

**Comment by cosmocoder** [comment]
@kaste I have the following in the Sublime Text console after enabling debug mode of SunlimeLinter:
```
SublimeLinter: log_handler.py:74      Logging installed; log level INFO
SublimeLinter: sublime_linter.py:68   debug mode: on
SublimeLinter: sublime_linter.py:69   version: 4.13.0
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 478, in run_callback
    expr()
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 619, in <lambda>
    run_callback('on_activated', callback, lambda: callback.on_activated(v))
  File "/Users/nilok/Library/Application Support/Sublime Text 3/Installed Packages/WordHighlight.sublime-package/word_highlight.py", line 125, in on_activated
    Pref.prev_selections = None
AttributeError: 'dict' object has no attribute 'prev_selections'
Path of tsserver.js: /Users/nilok/Library/Application Support/Sublime Text 3/Packages/TypeScript/tsserver/tsserver.js
Path of tsc.js: /Users/nilok/Library/Application Support/Sublime Text 3/Packages/TypeScript/tsserver/tsc.js
Trying to spawn node executable from: /usr/local/bin/node```

**Comment by kaste** [comment]
@cosmocoder Only the first three lines come from SublimeLinter actually. Are there some crashes already on startup when loading the plugins. What happens/gets dumped when you actually try to lint a file?

**Comment by cosmocoder** [comment]
When I make some edits and SublimeLinter tries to lint the file then there are no error messages in the console. I just see `SublimeLinter: sublime_linter.py:291  Delay linting '{file_name}.tsx' for 0.3s`

But no lint errors are reported inside the editor, even though I see linter error in the terminal with ESLint

**Comment by kaste** [comment]
@cosmocoder Hm, then either no linters are registered. Check in the console

```
from SublimeLinter.lint import persist
persist.linter_classes
```

or the eslint plugin is not configured to lint `tsx` files.

**Comment by cosmocoder** [comment]
I don't see the above line you specified in the console. But in another project where I have TSLint configured, and which was working even yesterday, stopped working today after doing the upgrade to 4.13
